# docs/sessions/generate-memory.ps1
# Purpose: extract decisions/learnings/todos blocks from a session markdown
# and append to memory/{decisions,learnings,todos}.md.
# Called by backup.ps1.

param(
    [string]$NewSessionPath = "",
    [string]$MemoryDir = ""
)

$ProjectRoot = "C:\Users\hecto\ZCodeProject"
$Docs = Join-Path $ProjectRoot "docs\sessions"
$Mem = if ($MemoryDir) { $MemoryDir } else { Join-Path $Docs "memory" }

if (-not (Test-Path $Mem)) {
    New-Item -ItemType Directory -Path $Mem -Force | Out-Null
}

if (-not $NewSessionPath) {
    Write-Host "[WARN] No session path given, skip memory update" -ForegroundColor Yellow
    exit 0
}

if (-not (Test-Path $NewSessionPath)) {
    Write-Host "[ERROR] Session path not found: $NewSessionPath" -ForegroundColor Red
    exit 1
}

$Session = Get-Content -Raw -Encoding UTF8 $NewSessionPath

# --- block extractor (regex without backticks) ---
function Extract-Block {
    param([string]$Text, [string]$Marker)
    # marker lines: ```marker ... ```
    $startMarker = '```' + $Marker
    $startIdx = $Text.IndexOf($startMarker)
    if ($startIdx -lt 0) { return $null }
    $afterOpen = $Text.IndexOf("`n", $startIdx)
    if ($afterOpen -lt 0) { return $null }
    $endIdx = $Text.IndexOf('```', $afterOpen + 1)
    if ($endIdx -lt 0) { return $null }
    return $Text.Substring($afterOpen + 1, $endIdx - $afterOpen - 1).Trim()
}

$Decisions = Extract-Block $Session 'decisions'
$Learnings = Extract-Block $Session 'learnings'
$Todos     = Extract-Block $Session 'todos'

function Append-Block {
    param([string]$File, [string]$Body, [string]$Header)
    if (-not $Body) { return }
    if (-not (Test-Path $File)) {
        Set-Content -Path $File -Value $Header -Encoding UTF8
    }
    $stamp = Get-Date -Format 'yyyy-MM-dd HH:mm'
    Add-Content -Path $File -Value "`n## $stamp" -Encoding UTF8
    Add-Content -Path $File -Value $Body -Encoding UTF8
    Write-Host "[OK] Appended to $File" -ForegroundColor Green
}

$DecisionsFile = Join-Path $Mem 'decisions.md'
$LearningsFile = Join-Path $Mem 'learnings.md'
$TodosFile     = Join-Path $Mem 'todos.md'

$Header = @"
# Project Memory: decisions / learnings / todos

> auto-generated by generate-memory.ps1
> appended after each backup
> edit manually if needed

---
"@

Append-Block $DecisionsFile $Decisions $Header
Append-Block $LearningsFile $Learnings $Header
Append-Block $TodosFile     $Todos     $Header

Write-Host "=== generate-memory.ps1 done ===" -ForegroundColor Cyan